security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    user: { password: 'pass', roles: ['ROLE_API_USER'] }
                    admin: { password: 'admin', roles: ['ROLE_ADMIN'] }

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: App\Security\Authentication\AuthenticationSuccessHandler

        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: ROLE_API_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_API_USER]
